export type Locale = "ar" | "en";

export const content = {
  ar: {
    common: {
      appName: "إنجاز",
      actions: {
        save: "حفظ",
        cancel: "إلغاء",
        delete: "حذف",
        edit: "تعديل",
        search: "بحث",
      },
      status: {
        loading: "جاري التحميل...",
        success: "تمت العملية بنجاح",
        error: "حدث خطأ",
      },
      goBack: "العودة للسابق",
      comingSoon: "قريباً",
      pagination: {
        first: "الأولى",
        last: "الأخيرة",
        previous: "السابق",
        next: "التالي",
      },
      toast: {
        success: "تمت العملية بنجاح",
        error: "حدث خطأ، يرجى المحاولة مرة أخرى",
        deleted: "تم الحذف بنجاح",
      },
      confirm: {
        deleteTitle: "تأكيد الحذف",
        deleteMessage:
          "هل أنت متأكد من حذف هذا العنصر؟ لا يمكن التراجع عن هذا الإجراء.",
        delete: "حذف",
        cancel: "إلغاء",
      },
    },
    auth: {
      login: {
        title: "تسجيل دخول",
        description:
          "مرحبا بك في لوحة تحكم انجاز معلم، سجل دخولك لمتابعة البيانات والإحصائيات",
        email: "البريد الإلكتروني",
        phone: "رقم الهاتف",
        phonePlaceholder: "مثال: mohammed@gmail.com",
        password: "كلمة المرور",
        passwordPlaceholder: "أدخل كلمة المرور",
        submit: "تسجيل دخول",
        forgotPassword: "نسيت كلمة المرور؟",
        errorGeneric: "فشل تسجيل الدخول، يرجى المحاولة مرة أخرى",
      },
      logout: "تسجيل الخروج",
    },
    dashboard: {
      title: "لوحة التحكم",
      welcome: "مرحباً بك في إنجاز",
      sidebar: {
        reports: "إحصائيات وتقارير",
        users: "إدارة العملاء",
        files: "إدارة الملفات",
        subscriptions: "إدارة الإشتراكات",
        ranks: "إدارة الرتب والبنود",
        academicYears: "إدارة السنوات الدراسية",
        profileTypes: "إدارة أنواع الملفات",
        assessments: "إدارة التقييمات",
        terms: "الشروط والأحكام",
        socials: "إدارة وسائل التواصل",
        logout: "تسجيل الخروج",
      },
      navbar: {
        logout: "تسجيل الخروج",
        language: "English",
      },
    },
    socials: {
      title: "إدارة وسائل التواصل",
      goBack: "العودة للسابق",
      socialAccounts: "حسابات التواصل الإجتماعي",
      contactInfo: "معلومات تواصل الموقع",
      instagram: "حساب انستجرام",
      snapchat: "حساب سناب شات",
      tiktok: "حساب تيك توك",
      x: "حساب إكس",
      facebook: "حساب فيسبوك",
      phoneNumber: "رقم الجوال",
      email: "البريد الإلكتروني",
      youtube: "قناة يوتيوب",
      enterAccountLink: "ادخل رابط الحساب",
      enterPhoneNumber: "ادخل رقم الجوال",
      enterEmail: "ادخل البريد الإلكتروني",
      enterChannelLink: "ادخل رابط القناة",
      save: "حفظ البيانات",
    },
    academicYears: {
      title: "إدارة السنوات الدراسية",
      addYear: "أضف سنة دراسية",
      createdYears: "السنوات الدراسية المنشئة",
      searchPlaceholder: "ابحث عن السنة الدراسية...",
      table: {
        year: "السنة الدراسية",
        status: "حالة السنة",
        subscription: "الإشتراك الخاص بالسنة",
        activeOffers: "العروض المفعلة",
        files: "ملفات الانجاز",
        action: "إجراء",
      },
      status: {
        active: "مفعلة",
        inactive: "غير مفعلة",
        expired: "منتهية",
      },
      pagination: {
        first: "الأولى",
        last: "الأخيرة",
        previous: "السابق",
        next: "التالي",
      },
      modal: {
        title: "إضافة سنة دراسية جديدة",
        hijriYear: "السنة الهجرية",
        gregorianYear: "السنة الميلادية",
        yearStatus: "حالة السنة الدراسية",
        hijriStartDate: "تاريخ بداية السنة هجري",
        hijriEndDate: "تاريخ نهاية السنة هجري",
        gregorianStartDate: "تاريخ بداية السنة ميلادي",
        gregorianEndDate: "تاريخ نهاية السنة ميلادي",
        enterYear: "ادخل السنة",
        enterDate: "ادخل التاريخ",
        add: "إضافة",
      },
      currency: "ريال سعودي",
      noOffers: "لا يوجد",
      viewFiles: "عرض ملفات السنة",
    },
    terms: {
      title: "الشروط والأحكام",
      textContent: "محتوى النص",
      save: "حفظ",
      preview: "معاينة",
      previewTitle: "معاينة الشروط والأحكام",
      subscriptionEnd: "انتهاء الإشتراك",
    },
    reviews: {
      title: "إدارة التقييمات",
      addReview: "أضف تقييم جديد",
      addReviewShort: "أضف تقييم",
      dateRange: "14 سبتمبر 2025 / 27 يناير 2026",
      daysAgo: "منذ",
      days: "أيام",
      publish: "نشر التقييم",
      unpublish: "عدم نشر التقييم",
      empty: {
        title: "لا يوجد تقييمات بعد",
      },
      pagination: {
        first: "الأولى",
        last: "الأخيرة",
        previous: "السابق",
        next: "التالي",
      },
      modal: {
        title: "إضافة تقييم جديد",
        clientName: "اسم العميل",
        clientNamePlaceholder: "ادخل اسم العميل ثنائي",
        jobTitle: "المسمى الوظيفي",
        jobTitlePlaceholder: "اختر المسمى الوظيفي",
        content: "محتوى التقييم",
        contentPlaceholder:
          "تجربة مرة ممتازة صراحة انصح فيها كل مدرس يبي يصمم ملف انجاز مميز ومختلف",
        selectRating: "حدد التقييم",
        clientImage: "صورة العميل",
        imageMaxSize: "يجب أن لا يزيد حجم الصورة عن 1 جيجا",
        uploadImage: "تحميل الصورة",
        showSiteLogo: "إظهار لوجو الموقع",
        add: "إضافة",
      },
      jobTitles: {
        expertTeacher: "معلم خبير",
        practiceTeacher: "معلم ممارس",
        advancedTeacher: "معلم متقدم",
      },
    },
    reports: {
      error: "فشل تحميل التقرير. يرجى تحديث الصفحة أو تسجيل الدخول مرة أخرى.",
      stats: {
        totalProfits: "إجمالي الأرباح",
        newUsers: "عدد المستخدمين الجدد",
        subscribers: "عدد المشتركين",
        publishedFiles: "عدد الملفات المنشورة",
        rial: "ريال",
        user: "مستخدم",
        subscriber: "مشترك",
        file: "ملف",
      },
      trend: {
        increase: "زيادة عن الشهر الماضي",
        decrease: "أقل من الشهر الماضي",
      },
      charts: {
        profitStats: "احصائيات الارباح",
        weekProfits: "الاسبوع/الأرباح",
        filesCreated: "عدد الملفات المنشأة",
        totalFiles: "ملف",
        vsLastMonth: "عن الشهر الماضي",
      },
      months: {
        jan: "يناير",
        feb: "فبراير",
        mar: "مارس",
        apr: "ابريل",
        may: "مايو",
        jun: "يونيو",
        jul: "يوليو",
        aug: "أغسطس",
        sep: "سبتمبر",
        oct: "أكتوبر",
        nov: "نوفمبر",
        dec: "ديسمبر",
      },
      subscriptions: {
        title: "أحدث الإشتراكات",
        timeAgo: "منذ",
        minutes: "دقيقة",
      },
      files: {
        title: "أحدث الملفات المنشئة",
        viewFile: "عرض الملف",
        published: "ملف منشور",
        unpublished: "ملف غير منشور",
        academicYear: "العام الدراسي:",
        createdAt: "تاريخ الإنشاء:",
      },
    },
  },
  en: {
    common: {
      appName: "Injaz",
      actions: {
        save: "Save",
        cancel: "Cancel",
        delete: "Delete",
        edit: "Edit",
        search: "Search",
      },
      status: {
        loading: "Loading...",
        success: "Operation completed successfully",
        error: "An error occurred",
      },
      goBack: "Go Back",
      comingSoon: "Coming Soon",
      pagination: {
        first: "First",
        last: "Last",
        previous: "Previous",
        next: "Next",
      },
      toast: {
        success: "Operation completed successfully",
        error: "An error occurred, please try again",
        deleted: "Deleted successfully",
      },
      confirm: {
        deleteTitle: "Confirm Delete",
        deleteMessage:
          "Are you sure you want to delete this item? This action cannot be undone.",
        delete: "Delete",
        cancel: "Cancel",
      },
    },
    auth: {
      login: {
        title: "Login",
        phone: "Phone Number",
        phonePlaceholder: "05xxxxxxxx",
        password: "Password",
        passwordPlaceholder: "Enter your password",
        submit: "Sign In",
        forgotPassword: "Forgot password?",
        errorGeneric: "Login failed, please try again",
      },
      logout: "Logout",
    },
    dashboard: {
      title: "Dashboard",
      welcome: "Welcome to Injaz",
      sidebar: {
        reports: "Statistics & Reports",
        users: "Client Management",
        files: "File Management",
        subscriptions: "Subscription Management",
        ranks: "Ranks & Items",
        academicYears: "Academic Years",
        profileTypes: "Profile Types",
        assessments: "Assessment Management",
        terms: "Terms & Conditions",
        socials: "Social Media Management",
        logout: "Logout",
      },
      navbar: {
        logout: "Logout",
        language: "العربية",
      },
    },
    socials: {
      title: "Social Media Management",
      goBack: "Go Back",
      socialAccounts: "Social Media Accounts",
      contactInfo: "Website Contact Info",
      instagram: "Instagram Account",
      snapchat: "Snapchat Account",
      tiktok: "TikTok Account",
      x: "X Account",
      facebook: "Facebook Account",
      phoneNumber: "Phone Number",
      email: "Email Address",
      youtube: "YouTube Channel",
      enterAccountLink: "Enter account link",
      enterPhoneNumber: "Enter phone number",
      enterEmail: "Enter email address",
      enterChannelLink: "Enter channel link",
      save: "Save Data",
    },
    academicYears: {
      title: "Academic Years Management",
      addYear: "Add Academic Year",
      createdYears: "Created Academic Years",
      searchPlaceholder: "Search for academic year...",
      table: {
        year: "Academic Year",
        status: "Status",
        subscription: "Year Subscription",
        activeOffers: "Active Offers",
        files: "Achievement Files",
        action: "Action",
      },
      status: {
        active: "Active",
        inactive: "Inactive",
        expired: "Expired",
      },
      pagination: {
        first: "First",
        last: "Last",
        previous: "Previous",
        next: "Next",
      },
      modal: {
        title: "Add New Academic Year",
        hijriYear: "Hijri Year",
        gregorianYear: "Gregorian Year",
        yearStatus: "Academic Year Status",
        hijriStartDate: "Hijri Start Date",
        hijriEndDate: "Hijri End Date",
        gregorianStartDate: "Gregorian Start Date",
        gregorianEndDate: "Gregorian End Date",
        enterYear: "Enter year",
        enterDate: "Enter date",
        add: "Add",
      },
      currency: "SAR",
      noOffers: "None",
      viewFiles: "View Year Files",
    },
    terms: {
      title: "Terms & Conditions",
      textContent: "Text Content",
      save: "Save",
      preview: "Preview",
      previewTitle: "Preview Terms & Conditions",
      subscriptionEnd: "Subscription Expiry",
    },
    reviews: {
      title: "Assessment Management",
      addReview: "Add New Review",
      addReviewShort: "Add Review",
      dateRange: "14 Sep 2025 / 27 Jan 2026",
      daysAgo: "ago",
      days: "days",
      publish: "Publish Review",
      unpublish: "Unpublish Review",
      empty: {
        title: "No reviews yet",
      },
      pagination: {
        first: "First",
        last: "Last",
        previous: "Previous",
        next: "Next",
      },
      modal: {
        title: "Add New Review",
        clientName: "Client Name",
        clientNamePlaceholder: "Enter client full name",
        jobTitle: "Job Title",
        jobTitlePlaceholder: "Select job title",
        content: "Review Content",
        contentPlaceholder:
          "An excellent experience, I recommend every teacher to create an achievement file",
        selectRating: "Select Rating",
        clientImage: "Client Image",
        imageMaxSize: "Image must not exceed 1 GB",
        uploadImage: "Upload Image",
        showSiteLogo: "Show Site Logo",
        add: "Add",
      },
      jobTitles: {
        expertTeacher: "Expert Teacher",
        practiceTeacher: "Practice Teacher",
        advancedTeacher: "Advanced Teacher",
      },
    },
    reports: {
      error: "Failed to load report. Please refresh the page or sign in again.",
      stats: {
        totalProfits: "Total Profits",
        newUsers: "New Users",
        subscribers: "Subscribers",
        publishedFiles: "Published Files",
        rial: "SAR",
        user: "user",
        subscriber: "subscriber",
        file: "file",
      },
      trend: {
        increase: "increase from last month",
        decrease: "decrease from last month",
      },
      charts: {
        profitStats: "Profit Statistics",
        weekProfits: "Week/Profits",
        filesCreated: "Files Created",
        totalFiles: "file",
        vsLastMonth: "from last month",
      },
      months: {
        jan: "Jan",
        feb: "Feb",
        mar: "Mar",
        apr: "Apr",
        may: "May",
        jun: "Jun",
        jul: "Jul",
        aug: "Aug",
        sep: "Sep",
        oct: "Oct",
        nov: "Nov",
        dec: "Dec",
      },
      subscriptions: {
        title: "Latest Subscriptions",
        timeAgo: "ago",
        minutes: "min",
      },
      files: {
        title: "Latest Created Files",
        viewFile: "View File",
        published: "Published",
        unpublished: "Unpublished",
        academicYear: "Academic Year:",
        createdAt: "Created At:",
      },
    },
  },
};

export function getTranslations(locale: Locale) {
  return content[locale];
}

export function getTranslation(
  locale: Locale,
  namespace: keyof (typeof content)[Locale],
  key?: string,
) {
  const ns = content[locale][namespace] as any;
  if (!key) return ns;
  return key.split(".").reduce((obj, k) => obj?.[k], ns);
}
